//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finisher.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finisher.Shared.Resources.Messages.fa", typeof(Messages_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کانکشن دیتابیس پیدا نشد.
        /// </summary>
        public static string ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبوری فعلی مورد نیاز است.
        /// </summary>
        public static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تایید ایمیل.
        /// </summary>
        public static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مورد نظر برای {0} قابل قبول نیست.
        /// </summary>
        public static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید وارد شده اشتباه است.
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مورد نظر باید بین {0} و {1} باشد. طول کنونی: {2}.
        /// </summary>
        public static string LengthBetween {
            get {
                return ResourceManager.GetString("LengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پیش فرض برای این مورد قابل قبول نیست.
        /// </summary>
        public static string NotDefaultValue {
            get {
                return ResourceManager.GetString("NotDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده با پترن {0} مچ نمی‌شود.
        /// </summary>
        public static string NotMatchedPattern {
            get {
                return ResourceManager.GetString("NotMatchedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید بیشتر از صفر باشد.
        /// </summary>
        public static string NotNegativeOrZero {
            get {
                return ResourceManager.GetString("NotNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} نمی‌تواند بعد از {1} باشد.
        /// </summary>
        public static string NotValidDateRange {
            get {
                return ResourceManager.GetString("NotValidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر پیدا نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مورد نظر نمی‌توان خالی باشد.
        /// </summary>
        public static string ValueCanNotBeNull {
            get {
                return ResourceManager.GetString("ValueCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between {0} and {1}. Current length: {2}
        /// </summary>
        public static string ShortLengthBetween {
            get {
                return ResourceManager.GetString("ShortLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be greater than zero.
        /// </summary>
        public static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not valid value
        /// </summary>
        public static string NotValidValue {
            get {
                return ResourceManager.GetString("NotValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not null
        /// </summary>
        public static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeGreaterThan 
        /// </summary>
        public static string DateTimeLessThanOrEqual  {
            get {
                return ResourceManager.GetString("DateTimeLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeGreaterThan 
        /// </summary>
        public static string DateTimeGreaterThan  {
            get {
                return ResourceManager.GetString("DateTimeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLength 
        /// </summary>
        public static string MinLength  {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFileType 
        /// </summary>
        public static string InvalidFileType  {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotValidId 
        /// </summary>
        public static string NotValidId  {
            get {
                return ResourceManager.GetString("NotValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyExist 
        /// </summary>
        public static string AlreadyExist  {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyExistItem 
        /// </summary>
        public static string AlreadyExistItem  {
            get {
                return ResourceManager.GetString("AlreadyExistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidRegex 
        /// </summary>
        public static string InvalidRegex  {
            get {
                return ResourceManager.GetString("InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidValueFor 
        /// </summary>
        public static string InvalidValueFor {
            get {
                return ResourceManager.GetString("InvalidValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound 
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token could not be decrypted.
        /// </summary>
        public static string TokenException {
            get {
                return ResourceManager.GetString("TokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string RequiredPhone {
            get {
                return ResourceManager.GetString("RequiredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiredToken
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFoundFor
        /// </summary>
        public static string NotFoundFor {
            get {
                return ResourceManager.GetString("NotFoundFor", resourceCulture);
            }
        }
    }
}
