global using Ardalis.Specification;
global using Finisher.Application.Models;
global using Finisher.Domain.Models;
global using Finisher.Shared.Consts;
global using Finisher.Shared.Extensions;
global using Finisher.Shared.Resources;
global using FluentValidation;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
